[tool.poetry]
name = "ask_chatgpt"
version = "0.1.0"
description = ""
authors = ["Carl Kristensen <>"]

[tool.poetry.dependencies]
python = "^3.11"
openai = "^0.26.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
